# -*- coding: utf-8 -*-
"""Task09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Addt-GH4HzAs_ydU-RV7jh8HtTzh06N5

**Task 09: Data linking**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef, OWL
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

for s,p,o in g1:
  print(s,p,o)

for s,p,o in g2:
  print(s,p,o)

vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
apodos1 = g1.triples((None, vcard.Given, None))
apellidos1 = g1.triples((None, vcard.Family, None))

lista1 = []
lista2 = []

for s,p,o in apodos1:
  for s1,p1,o1 in g2.triples((None, vcard.Given, o)):
    lista1 += [(s,s1)]

for s,p,o in apellidos1:
  for s1,p1,o1 in g2.triples((None, vcard.Family, o)):
    lista2 += [(s,s1)]
for elemento in lista2:
  if elemento in lista1:
    print(elemento)
    g3.add((elemento[0], OWL.sameAs, elemento[1]))

"""Vemos que acaban excluidos del g3 John Smith, ya que su apodo en g2 es Jonathan Smith, mientras que el John Smith del g1 tiene como apodo John, y también Harry Potter, al no tener apellido asignado en g1."""

for s,p,o in g3:
  print(s,p,o)