SELECT ?sujeto ?enlace
WHERE {?sujeto http://www.w3.org/2002/07/owl#sameAs ?enlace}

SELECT ?sujeto ?parada
WHERE {?sujeto <http://museosymonumentos.es/conocemadrid/ontology/culturalEntities#hasNearbyStop> ?parada}

SELECT ?sujeto ?barrio
WHERE {?sujeto <http://www.w3.org/2006/vcard/nshasAddress> ?direcc.
	?direcc <http://rdfs.co/juso/neighborhood> ?barrio}
	
SELECT ?sujeto ?distrito
WHERE {?sujeto <http://www.w3.org/2006/vcard/nshasAddress> ?direcc.
	?direcc <https://dbpedia.org/ontology/district> ?distrito}

SELECT ?sujeto ?direcc ?coord
WHERE {?sujeto <http://www.w3.org/2006/vcard/nshasAddress> ?direcc.
	?direcc <http://www.schema.org/geo> ?coord}

SELECT ?sujeto ?lat ?long
WHERE {?sujeto <http://www.w3.org/2006/vcard/nshasAddress> ?direcc.
	?direcc <http://www.schema.org/geo> ?coord.
	?coord <http://www.w3.org/2003/01/geo/wgs84_pos/lat> ?lat.
	?coord <http://www.w3.org/2003/01/geo/wgs84_pos/long> ?long}

SELECT ?sujeto ?access
WHERE {?sujeto <http://museosymonumentos.es/conocemadrid/ontology/culturalEntities#accessibility> ?access}

SELECT ?sujeto ?nombre
WHERE {?sujeto <https://dbpedia.org/ontology/name> ?nombre}

SELECT ?sujeto ?web
WHERE {?sujeto <http://www.schema.org/webSite> ?web}

SELECT ?sujeto ?email
WHERE {?sujeto <http://www.w3.org/2006/vcard/nshasEmail> ?email}

SELECT ?sujeto ?telef
WHERE {?sujeto <http://www.schema.org/telephone> ?telef}

SELECT ?sujeto ?stop
WHERE {?sujeto <http://museosymonumentos.es/conocemadrid/ontology/culturalEntities#hasNearbyStop> ?stop}

