# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hSv61ejXESrp34CUz1PqZCsoA43tzc8y

**Task 06: Modifying RDF(s)**
"""

#pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2020-2021/master/Assignment4"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS

with open('example5.rdf', 'r') as f:
  g = Graph()
  g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
  g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
  g.parse(f, format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
#for s, p, o in g:
#  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

**TASK 6.2: Add "Researcher" as a subclass of "Person"**

**TASK 6.3: Create a new individual of Researcher named "Jane Smith"**

**TASK 6.4: Add to the individual JaneSmith the fullName, given and family names**

**TASK 6.5: Add UPM as the university where John Smith works**
"""

"TASK 6.1:"
g.add((ns.University, RDF.type, RDFS.Class))
#for s,p,o in g:
 # print(s,p,o)

"TASK 6.2:"
g.add((ns.Researcher, RDFS.subClassOf, ns.Person))
#for s,p,o in g:
  #print(s,p,o)

"TASK 6.3:"
g.add((ns.JaneSmith,RDF.type,ns.Researcher))
#for s,p,o in g:
  #print(s,p,o)

"TASK 6.4:"
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
g.add((ns.JaneSmith, VCARD.FN, Literal('Jane Smith', datatype=XSD.string)))
g.add((ns.JaneSmith, VCARD.Family, Literal('Smith', datatype=XSD.string)))
g.add((ns.JaneSmith, VCARD.Given, Literal('Jane', datatype=XSD.string)))
#for s,p,o in g:
  #print(s,p,o)

"TASK 6.5:"
g.add((ns.UPM, RDF.type, ns.University))
g.add((ns.JohnSmith, VCARD.Works, ns.UPM))
for s,p,o in g:
  print(s,p,o)